language: java
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
    branches:
    - master


    sonarcloud:
      organization: $SONAR_ORGANIZATION
      token:
        secure: $SONAR_TOKEN
  script:
  - sonar-scanner

services:
- postgresql

before_install:
- chmod +x gradlew
- psql -c 'create database message_db;' -U postgres
- psql -c 'alter user postrgres with password 'postgres';' -U postgres

script:
- ./gradlew wrapper
- ./gradlew check

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
